### ISSUE TITLE
Error when running git submodule update --init --recursive

### ISSUE THREAD

**Issue by remi0s** [ColinKinloch/LatinIME_apk#1]
I'm trying to build the latinime in android studio using your guide but failed to download the latinime module with the following error:

$ git submodule update --init --recursive
Submodule 'LatinIME' (https://github.com/ColinKinloch/LatinIME.git) registered for path 'LatinIME'
Submodule 'inputmethodcommon' (https://android.googlesource.com/platform/frameworks/opt/inputmethodcommon) registered for path 'inputmethodcommon'
Cloning into 'C:/Users/remio/Desktop/LatinIME_apk/LatinIME'...
Cloning into 'C:/Users/remio/Desktop/LatinIME_apk/inputmethodcommon'...
error: Server does not allow request for unadvertised object c9c580b31c0d1835e31b2e2ceee13da04284cd69
Fetched in submodule path 'LatinIME', but it did not contain c9c580b31c0d1835e31b2e2ceee13da04284cd69. Direct fetching of that commit failed.

**Comment by ColinKinloch** [comment]
This should be fixed by https://github.com/ColinKinloch/LatinIME_apk/commit/1b722620bc14a2c46749a1633a2315927242fa0f and https://github.com/ColinKinloch/LatinIME_apk/commit/7e38fe4b5465e78bafbf7317d06f599bd3eb867d
